# Configuration for Cargo, the Rust package manager
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32G474RETx --log-format=oneline"
# Specify custom linker and linker arguments
rustflags = [
  "-C", "link-arg=-Tlink.x", # 
  "-C", "link-arg=-Tdefmt.x"
]
# Set the build target for embedded ARM Cortex-M4F
[build]
target = "thumbv7em-none-eabihf"

# Set environment variables for the build process
[env]
DEFMT_LOG = "info"